### ISSUE TITLE
Error resetting ballot

### ISSUE THREAD

**Issue by meglister** [voteagora/agora-next#575]
**Describe the bug**
When I try to reset my ballot, I get an "error resetting ballot" toast and an error in the console. It looks like this is API related.

**To Reproduce**
1. Log into RF6 with a badgeholder wallet: https://develop-op-rf-6.up.railway.app/ballot
2. I was evaluating the Governance Infra + Tooling category
3. Rate all projects
4. Choose an allocation method. I also edited several of the individual allocations
5. Click "reset" and observe error

**Expected behavior**
Ballot should be reset to 0 allocation state for all projects

**Screenshots**
https://www.loom.com/share/1de49700ddd54412851b29a396b02f33

**Comment by meglister** [comment]
Also noting that this is only happening for one of my testing wallets. The other wallet is working fine! You can see that experience recorded here, and I immediately logged back in with the problem wallet and experienced the same error on resetting the ballot: https://www.loom.com/share/a638cc87a0234ed0bca4eb61914cfc74?sid=ff0e095d-55be-461a-97d3-432eedc0dabd

**Comment by stepandel** [comment]
we don't have ballot resetting functionality in the API. What endpoint are you calling and with what data? @meglister
