### ISSUE TITLE
Error submitting ballot

### ISSUE THREAD

**Issue by meglister** [voteagora/agora-next#576]
**Describe the bug**
When I try to submit my ballot, I get an error and am not able to submit it.

**To Reproduce**
1. Log into RF6. I am using a badgeholder wallet in the category Gov Infra + Tooling
2. Complete budget allocations and project rankings
3. Select allocation method
4. Try to submit ballot. Sign the message in your wallet
5. Observe error

**Expected behavior**
Ballot should have submitted successfully

**Screenshots**
https://www.loom.com/share/8387448b5f5d497aa500ae1ba89ba69f

**Comment by stepandel** [comment]
fixed in https://github.com/voteagora/agora-next/commit/a155cad6fd99d7ad6441f572928f3edca9e9ad7d
